{% set name = "CarnaPy" %}
{% set version = "$VERSION_CARNA_PY" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: "https://pypi.io/packages/source/{{ name[0]|lower }}/{{ name|lower }}/{{ name }}-{{ version }}.tar.gz"

build:
  number: 0

requirements:
  build:
    - git
    - cmake
    - pybind11
    - boost-cpp
    - eigen
  host:
    - pyyaml
    - pip
    - python
    - numpy
    - matplotlib # for tests only
    - scipy      # for tests only
  run:
    - numpy
    - python

test:
  imports:
    - carna
    - carna.py
    - carna.base
    - carna.helpers
    - carna.presets
    - carna.egl

about:
  home: "http://evoid.de"
  license: BSD
  license_family: BSD
  license_file: 
  summary: "Real-time 3D visualization for biomedical data and beyond"
  doc_url: 
  dev_url: "https://github.com/kostrykin/CarnaPy"

extra:
  recipe-maintainers:
    - kostrykin
