name: Build CarnaPy and Docker image

on:
  push:
    branches:
      - 'master'
      - 'dev**'
    tags:
      - '**'

jobs:
  build_carnapy:
    name: Build CarnaPy
    runs-on: ubuntu-latest
    steps:
      -
        name: Initialize
        uses: actions/checkout@v2
      -
        uses: conda-incubator/setup-miniconda@v2
        with:
          miniconda-version: 'latest'
          channels: conda-forge, defaults
          use-only-tar-bz2: true  # IMPORTANT: This needs to be set for caching to work properly!
          auto-update-conda: true
          auto-activate-base: true
      -
        name: Set environment variables
        run: echo "CONDA_PREFIX=$CONDA" >> $GITHUB_ENV
      -
        name: Build and install
        run: sh build.sh
      - name: Prepare artifact
        run: |
          mkdir /tmp/dist
          cp /usr/local/lib/libCarna-*.so /tmp/dist
          rm /tmp/dist/libCarna-*d.so
          cp $(find /home/runner/work -name '*.whl') /tmp/dist/
      -
        uses: actions/upload-artifact@v3
        with:
          name: dist
          path: |
             /tmp/dist
#            /usr/local/lib/libCarna-*.so
#            !/usr/local/lib/libCarna-*d.so
#            /home/runner/work/**/CarnaPy/dist/*.whl
